name: test

on: [push, pull_request]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        run: npm i -g pnpm@9
      - name: Install dependencies
        run: pnpm install
      - name: Run unit test
        run: pnpm run test:unit
      - name: Run build
        run: pnpm run build:lib
